export const demoIssues = [
  {
    id: "issue-delhi-food",
    location: "Delhi",
    issueType: "Food shortage",
    severity: 4,
    severityLabel: "Critical",
    lat: 28.6139,
    lng: 77.209,
    status: "Open - urgent",
    createdAt: "2026-04-28T08:00:00.000Z",
    trend: "rising",
  },
  {
    id: "issue-mumbai-medical",
    location: "Mumbai",
    issueType: "Medical camp support",
    severity: 3,
    severityLabel: "High",
    lat: 19.076,
    lng: 72.8777,
    status: "Open - urgent",
    createdAt: "2026-04-28T08:10:00.000Z",
    trend: "rising",
  },
  {
    id: "issue-bengaluru-shelter",
    location: "Bengaluru",
    issueType: "Shelter coordination",
    severity: 2,
    severityLabel: "Medium",
    lat: 12.9716,
    lng: 77.5946,
    status: "Open",
    createdAt: "2026-04-28T08:20:00.000Z",
    trend: "stable",
  },
  {
    id: "issue-lucknow-rescue",
    location: "Lucknow",
    issueType: "Flood rescue assistance",
    severity: 4,
    severityLabel: "Critical",
    lat: 26.8467,
    lng: 80.9462,
    status: "Open - urgent",
    createdAt: "2026-04-28T08:30:00.000Z",
    trend: "rising",
  },
  {
    id: "issue-jaipur-education",
    location: "Jaipur",
    issueType: "Education material shortage",
    severity: 2,
    severityLabel: "Medium",
    lat: 26.9124,
    lng: 75.7873,
    status: "Open",
    createdAt: "2026-04-28T08:40:00.000Z",
    trend: "stable",
  },
  {
    id: "issue-hyderabad-mental",
    location: "Hyderabad",
    issueType: "Mental health counseling",
    severity: 3,
    severityLabel: "High",
    lat: 17.385,
    lng: 78.4867,
    status: "Open - urgent",
    createdAt: "2026-04-28T08:50:00.000Z",
    trend: "rising",
  },
];

export const demoVolunteers = [
  {
    id: "vol-priya",
    name: "Priya Sharma",
    location: "Delhi",
    skills: ["Medical", "Counseling"],
    availability: "Immediate",
    createdAt: "2026-04-28T08:00:00.000Z",
    acceptedTaskIds: [],
  },
  {
    id: "vol-rahul",
    name: "Rahul Verma",
    location: "Lucknow",
    skills: ["Rescue", "Logistics"],
    availability: "Immediate",
    createdAt: "2026-04-28T08:05:00.000Z",
    acceptedTaskIds: [],
  },
  {
    id: "vol-aisha",
    name: "Aisha Khan",
    location: "Mumbai",
    skills: ["Medical", "Logistics"],
    availability: "This week",
    createdAt: "2026-04-28T08:10:00.000Z",
    acceptedTaskIds: [],
  },
  {
    id: "vol-rohan",
    name: "Rohan Nair",
    location: "Bengaluru",
    skills: ["Education", "Counseling"],
    availability: "Weekend",
    createdAt: "2026-04-28T08:20:00.000Z",
    acceptedTaskIds: [],
  },
];

export const demoAssignments = [];
